services:
  app:
    build:
      context: .
      target: test
    volumes:
      - ./final-project-tests:/app/final-project-tests
    ports:
      - "5001:5001"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Pass1234"
      ACCEPT_EULA: "Y"
