services:
  api:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Pass1234"
      ACCEPT_EULA: "Y"
